name: Publish Docker

# Controls when the action will run. Triggers the workflow on push or pull
# request events but only for the master branch
on:
    push:
        branches:
            - master
        # Publish `v1.2.3` tags as releases.
        # tags:
        #   - v*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build-and-publish:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Build
              run: |
                  docker build -f Containerfile -t bot .

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Publish to Registry
              run: |
                  REPO=ghcr.io/$(echo ${{ github.repository }} | tr '[A-Z]' '[a-z]')
                  VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

                  docker tag bot $REPO/bot:$VERSION
                  docker push $REPO/bot:$VERSION

                  # Use Docker `latest` tag convention
                  [ "$VERSION" == "master" ] && VERSION=latest

                  echo $REPO
                  echo $VERSION

                  docker tag bot $REPO/bot:$VERSION
                  docker push $REPO/bot:$VERSION
