# This is a basic workflow to help you get started with Actions

name: Deploy to Raspberry Pi

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ wouters-main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    
    outputs:
      tag_name: ${{ steps.set_tag_name.outputs.tag_name }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set TAG_NAME
        id: set_tag_name
        run: echo "::set-output name=tag_name::$(date +%s)"
        
      - name: Create a docker image
        run: |
          cd src/
          docker build -t rpi-cd-tutorial:${{ steps.set_tag_name.outputs.tag_name }} .
  deploy:
    runs-on: self-hosted
    needs: build
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Kill npm
        run: pkill npm || true
        
      - name: Run npm
        run: npm start